export default {
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  NOTIFICATION_BADGE_CHANGE: "NOTIFICATION_BADGE_CHANGE",

  STORE_LOADING: "STORE_LOADING",
  STORE_SUCCESS: "STORE_SUCCESS",
  STORE_ERROR: "STORE_ERROR",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
}