export default {
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  NOTIFICATION_BADGE_CHANGE: "NOTIFICATION_BADGE_CHANGE",

  STORE_LOADING: "STORE_LOADING",
  STORE_SUCCESS: "STORE_SUCCESS",
  STORE_ERROR: "STORE_ERROR",

  ADD_FACEBOOK_TOKEN_SUCCESS: "ADD_FACEBOOK_TOKEN_SUCCESS",
  PROFILE_LOADED: "PROFILE_LOADED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
}