# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn_mbookreader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn_mbookreader
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  target 'rn_mbookreaderTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'rn_mbookreader-tvOSTests' do
      inherit! :search_paths
      # Pods for testing
  end

end
